=== Alex-st/FinalProjects/XMLParsers/planes2.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:params="http://www.w3.org"
        elementFormDefault="qualified">
 
    <xs:element name="root" type="rootType" />
    <xs:complexType name="rootType">
        <xs:sequence>
            <xs:element name="plane" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        
                        <xs:element name="model" type="xs:string"/>
                        <xs:element name="origin" type="xs:string"/>
                        
                        <xs:element name="type">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="bomber"/>
                                    <xs:enumeration value="interceptor"/>
                                    <xs:enumeration value="fighter"/>
                                </xs:restriction>
                            </xs:simpleType> 
                        </xs:element>
                        
                        <xs:element name="parameters" type="params:Params"/>
                        <xs:element name="price" type="xs:int"/>
                        
                    </xs:sequence>       
                    <xs:attribute name="id" type="xs:ID" use="required"/> 
                </xs:complexType> 
                
            </xs:element>   
        </xs:sequence>
        
        
    </xs:complexType>
        
    <xs:complexType name="Params" > 
            <xs:sequence>
                <xs:element name="Length" type="xs:int"/>
                <xs:element name="Width" type="xs:int"/>
                <xs:element name="Height" type="xs:int"/>
                
            </xs:sequence>      
            
    </xs:complexType> 
    
</xs:schema>

=== Alex-st/FinalProjects/FinalProject3/Final/worklist2.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="planes2.xsd"
    xmlns="http://www.w3.org"
    xmlns:params="http://www.w3.org">
    <plane id="a001">
        <model>Supermarine Spitfire</model>
        <origin>GB</origin>
        <type>fighter</type>
        <parameters>
            <params:Length>4</params:Length>
            <params:Width>5</params:Width>
            <params:Height>3</params:Height>
        </parameters>
        <price>500</price>
    </plane>
    <plane id="b2">
        <model>Nortrope B2</model>
        <origin>USA</origin>
        <type>bomber</type>
        <parameters>
            <params:Length>10</params:Length>
            <params:Width>15</params:Width>
            <params:Height>5</params:Height>
        </parameters>
        <price>5500</price>
    </plane>
</root>
